#!/usr/bin/env python3
"""
Organize Photos - Standalone script to organize photos into folders based on tags.json.
Reads the tags.json file generated by photo_tagger.py and copies the corresponding
photos into subdirectories named after the tagged people.
"""

import json
import shutil
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Organize photos into folders based on tags.json.")
    parser.add_argument("--tags", "-t", required=True, help="Path to the tags.json file")
    parser.add_argument("--output", "-o", default="results/organized", help="Output directory for organized folders (default: results/organized)")
    args = parser.parse_args()

    tags_file = Path(args.tags)
    output_dir = Path(args.output)

    if not tags_file.exists():
        print(f"❌ Error: Tags file '{tags_file}' not found.")
        return

    try:
        with open(tags_file, "r") as f:
            tags = json.load(f)
    except json.JSONDecodeError:
        print(f"❌ Error: Could not parse JSON from '{tags_file}'.")
        return

    print(f"📂 Read {len(tags)} tag entries. Organizing photos into '{output_dir}'...")

    copied_count = 0
    missing_count = 0
    
    for entry in tags:
        person = entry.get("person")
        if not person:
            person = "Unknown"
            
        img_path = Path(entry.get("image_path", ""))
        
        if not img_path.exists():
            missing_count += 1
            continue
            
        # Create person's directory
        target_dir = output_dir / person
        target_dir.mkdir(parents=True, exist_ok=True)
        
        # Copy the file
        target_path = target_dir / img_path.name
        
        # Only copy if it doesn't already exist to save time on re-runs
        if not target_path.exists():
            shutil.copy2(img_path, target_path)
            copied_count += 1

    print("-" * 40)
    print(f"✅ Successfully copied {copied_count} photos into folders.")
    if missing_count > 0:
        print(f"⚠️  Skipped {missing_count} tags because the original photo could not be found.")
    print(f"📁 Location: {output_dir.resolve()}")

if __name__ == "__main__":
    main()